// Generated by wrangler types / extended manually
interface Env {
    ASSETS: Fetcher;
    BREVO_API_KEY: string;
}

// Extend Astro's App.Locals so runtime env is typed
declare namespace App {
    interface Locals {
        runtime: {
            env: Env;
        };
    }
}
